//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lob.Mvvm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lob.Mvvm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while deleting..
        /// </summary>
        public static string Error_Deleting {
            get {
                return ResourceManager.GetString("Error_Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while loading..
        /// </summary>
        public static string Error_Loading {
            get {
                return ResourceManager.GetString("Error_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation failded.
        /// </summary>
        public static string Error_NavigationFailed {
            get {
                return ResourceManager.GetString("Error_NavigationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while refreshing..
        /// </summary>
        public static string Error_Refreshing {
            get {
                return ResourceManager.GetString("Error_Refreshing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route &apos;{0}&apos; doesnt exist, please contact the support team..
        /// </summary>
        public static string Error_RouteMissing {
            get {
                return ResourceManager.GetString("Error_RouteMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while saving..
        /// </summary>
        public static string Error_Saving {
            get {
                return ResourceManager.GetString("Error_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred while searching..
        /// </summary>
        public static string Error_Searching {
            get {
                return ResourceManager.GetString("Error_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled error has occurred. Please contact technical support..
        /// </summary>
        public static string Error_Unhandled {
            get {
                return ResourceManager.GetString("Error_Unhandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string Label_ListTitle {
            get {
                return ResourceManager.GetString("Label_ListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Label_ViewModelTitle {
            get {
                return ResourceManager.GetString("Label_ViewModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Lable_SearchTitle {
            get {
                return ResourceManager.GetString("Lable_SearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the record : {0}  ?.
        /// </summary>
        public static string Message_DeleteConfirm {
            get {
                return ResourceManager.GetString("Message_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting please wait....
        /// </summary>
        public static string Message_Deleting {
            get {
                return ResourceManager.GetString("Message_Deleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading please wait....
        /// </summary>
        public static string Message_Loading {
            get {
                return ResourceManager.GetString("Message_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing please wait....
        /// </summary>
        public static string Message_Refreshing {
            get {
                return ResourceManager.GetString("Message_Refreshing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save completed successfully..
        /// </summary>
        public static string Message_SaveSucceded {
            get {
                return ResourceManager.GetString("Message_SaveSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving please wait....
        /// </summary>
        public static string Message_Saving {
            get {
                return ResourceManager.GetString("Message_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching please wait....
        /// </summary>
        public static string Message_Searching {
            get {
                return ResourceManager.GetString("Message_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IconDataAdded.
        /// </summary>
        public static string UriIcon_Added {
            get {
                return ResourceManager.GetString("UriIcon_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IconDataDeleted.
        /// </summary>
        public static string UriIcon_Deleted {
            get {
                return ResourceManager.GetString("UriIcon_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IconDataError.
        /// </summary>
        public static string UriIcon_Error {
            get {
                return ResourceManager.GetString("UriIcon_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IconDataErrorOn.
        /// </summary>
        public static string UriIcon_ErrorOn {
            get {
                return ResourceManager.GetString("UriIcon_ErrorOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IconDataInfo.
        /// </summary>
        public static string UriIcon_Info {
            get {
                return ResourceManager.GetString("UriIcon_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IconDataModified.
        /// </summary>
        public static string UriIcon_Modified {
            get {
                return ResourceManager.GetString("UriIcon_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IconDataView.
        /// </summary>
        public static string UriIcon_View {
            get {
                return ResourceManager.GetString("UriIcon_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IconDataEdit.
        /// </summary>
        public static string UriIcon_ViewEdit {
            get {
                return ResourceManager.GetString("UriIcon_ViewEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IconDataList.
        /// </summary>
        public static string UriIcon_ViewList {
            get {
                return ResourceManager.GetString("UriIcon_ViewList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IconDataListEdit.
        /// </summary>
        public static string UriIcon_ViewListEdit {
            get {
                return ResourceManager.GetString("UriIcon_ViewListEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IconDataNew.
        /// </summary>
        public static string UriIcon_ViewNew {
            get {
                return ResourceManager.GetString("UriIcon_ViewNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IconDataSearchList.
        /// </summary>
        public static string UriIcon_ViewSearch {
            get {
                return ResourceManager.GetString("UriIcon_ViewSearch", resourceCulture);
            }
        }
    }
}
